version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - frontend
      - backend
      - monitoring

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/voting_system?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
      - monitoring
    volumes:
      - ./backend/uploads:/app/uploads

  mongodb:
    restart: always
    image: mongo:7
    environment:
      - MONGO_INITDB_DATABASE=voting_system
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data1:/data/db
    networks:
      - frontend
      - backend
      - monitoring

volumes:
  mongodb_data1:

networks:
  frontend:
    external: true
  backend:
    external: true
  monitoring:
    external: true